name: test-and-deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  # Optional: run tests first
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install deps (optional)
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      # - name: Run tests
      #   run: pytest -q

  docker:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            docker.io/avneetsag/fastapi:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

           deploy-azure:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
      - name: 'Run Azure CLI commands'
        run: |
          az containerapp up \
            --name my-container-app \
            --resource-group my-container-apps \
            --location centralus \
            --environment 'my-container-apps' \
            --image avneetsag/fastapi:latest \
            --target-port 80 \
            --ingress external \
            --query properties.configuration.ingress.fqdn
