name: Incident_test_and_deploy

on:
  push:
    branches: [ main ]
    paths:
      - 'microservices/1.incident/**'          
      - '.github/workflows/incident.yml'       
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: microservices/1.incident   
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install deps (optional)
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
  

  docker:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set image meta
        id: meta
        run: |
          echo "REPO=docker.io/avneetsag/fastapi" >> $GITHUB_OUTPUT   
          echo "TAG=${{ github.sha }}" >> $GITHUB_OUTPUT             

      - name: Build & push
        uses: docker/build-push-action@v6
        with:
          context: microservices/1.incident
          file: microservices/1.incident/Dockerfile
          push: true
          tags: |
            ${{ steps.meta.outputs.REPO }}:${{ steps.meta.outputs.TAG }}
            ${{ steps.meta.outputs.REPO }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
